"""empty message

Revision ID: bb70f2de7fb7
Revises: 3b5f7e1b3895
Create Date: 2022-04-11 12:42:47.238852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb70f2de7fb7'
down_revision = '3b5f7e1b3895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_calories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('breakfast', sa.String(length=600), nullable=True),
    sa.Column('lunch', sa.String(length=600), nullable=True),
    sa.Column('dinner', sa.String(length=600), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_calories')
    # ### end Alembic commands ###
